export declare const ClusterCommands: readonly ["CLUSTER", "CLUSTER BUMPEPOCH", "CLUSTER COUNT-FAILURE-REPORTS", "CLUSTER COUNTKEYSINSLOT", "CLUSTER DELSLOTS", "CLUSTER FAILOVER", "CLUSTER FLUSHSLOTS", "CLUSTER FORGET", "CLUSTER GETKEYSINSLOT", "CLUSTER INFO", "CLUSTER KEYSLOT", "CLUSTER MEET", "CLUSTER MYID", "CLUSTER NODES", "CLUSTER REPLICATE", "CLUSTER RESET", "CLUSTER SAVECONFIG", "CLUSTER SET-CONFIG-EPOCH", "CLUSTER SETSLOT", "CLUSTER SLAVES", "CLUSTER REPLICAS", "CLUSTER SLOTS", "READONLY", "READWRITE"];
export declare type ClusterCommandType = typeof ClusterCommands[number];
export declare const ConnectionCommands: readonly ["AUTH", "CLIENT CACHING", "CLIENT ID", "CLIENT INFO", "CLIENT KILL", "CLIENT LIST", "CLIENT GETNAME", "CLIENT GETREDIR", "CLIENT PAUSE", "CLIENT REPLY", "CLIENT SETNAME", "CLIENT TRACKING", "CLIENT UNBLOCK", "ECHO", "HELLO", "PING", "QUIT", "RESET", "SELECT"];
export declare type ConnectionCommandType = typeof ConnectionCommands[number];
export declare const GeoCommands: readonly ["GEOADD", "GEOHASH", "GEOPOS", "GEODIST", "GEORADIUS", "GEORADIUSBYMEMBER"];
export declare type GeoCommandType = typeof GeoCommands[number];
export declare const HashesCommands: readonly ["HDEL", "HEXISTS", "HGET", "HGETALL", "HINCRBY", "HINCRBYFLOAT", "HKEYS", "HLEN", "HMGET", "HMSET", "HSET", "HSETNX"];
export declare type HashesCommandType = typeof HashesCommands[number];
export declare const HyperLogLogCommands: readonly ["PFADD", "PFCOUNT", "PFMERGE"];
export declare type HyperLogLogCommandType = typeof HyperLogLogCommands[number];
export declare const KeysCommands: readonly ["COPY", "DEL", "DUMP", "EXISTS", "EXPIRE", "EXPIREAT", "KEYS", "MIGRATE", "MOVE", "OBJECT", "PERSIST", "PEXPIRE", "PEXPIREAT", "PTTL", "RANDOMKEY", "RENAME", "RENAMENX", "RESTORE", "SORT", "TOUCH", "TTL", "TYPE", "UNLINK", "WAIT", "SCAN"];
export declare type KeysCommandType = typeof KeysCommands[number];
export declare const ListsCommands: readonly ["BLPOP", "BRPOP", "BRPOPLPUSH", "BLMOVE", "LINDEX", "LINSERT", "LLEN", "LPOP", "LPOS", "LPUSH", "LPUSHX", "LRANGE", "LREM", "LSET", "LTRIM", "RPOP", "RPOPLPUSH", "LMOVE", "RPUSH", "RPUSHX"];
export declare type ListsCommandType = typeof ListsCommands[number];
export declare const PubSubCommands: readonly ["PSUBSCRIBE", "PUBSUB", "PUBLISH", "PUNSUBSCRIBE", "SUBSCRIBE", "UNSUBSCRIBE"];
export declare type PubSubCommandType = typeof PubSubCommands[number];
export declare const ScriptingCommands: readonly ["EVAL", "EVALSHA", "SCRIPT DEBUG", "SCRIPT EXISTS", "SCRIPT FLUSH", "SCRIPT KILL", "SCRIPT LOAD"];
export declare type ScriptingCommandType = typeof ScriptingCommands[number];
export declare const ServerCommands: readonly ["ACL LOAD", "ACL SAVE", "ACL LIST", "ACL USERS", "ACL GETUSER", "ACL SETUSER", "ACL DELUSER", "ACL CAT", "ACL GENPASS", "ACL WHOAMI", "ACL LOG", "ACL HELP", "BGREWRITEAOF", "BGSAVE", "COMMAND", "COMMAND COUNT", "COMMAND GETKEYS", "COMMAND INFO", "CONFIG GET", "CONFIG REWRITE", "CONFIG SET", "CONFIG RESETSTAT", "DBSIZE", "DEBUG OBJECT", "DEBUG SEGFAULT", "FLUSHALL", "FLUSHDB", "INFO", "LOLWUT", "LASTSAVE", "MEMORY DOCTOR", "MEMORY HELP", "MEMORY MALLOC-STATS", "MEMORY PURGE", "MEMORY STATS", "MEMORY USAGE", "MODULE LIST", "MODULE LOAD", "MODULE UNLOAD", "MONITOR", "ROLE", "SAVE", "SHUTDOWN", "SLAVEOF", "REPLICAOF", "SLOWLOG", "SWAPDB", "SYNC", "PSYNC", "TIME", "LATENCY DOCTOR", "LATENCY GRAPH", "LATENCY HISTORY", "LATENCY LATEST", "LATENCY RESET", "LATENCY HELP"];
export declare type ServerCommandType = typeof ServerCommands[number];
export declare const SetsCommands: readonly ["SADD", "SCARD", "SDIFF", "SDIFFSTORE", "SINTER", "SINTERSTORE", "SISMEMBER", "SMISMEMBER", "SMEMBERS", "SMOVE", "SPOP", "SRANDMEMBER", "SREM", "SUNION", "SUNIONSTORE", "SSCAN"];
export declare type SetsCommandType = typeof SetsCommands[number];
export declare const SortedSetsCommands: readonly ["BZPOPMIN", "BZPOPMAX", "ZADD", "ZCARD", "ZCOUNT", "ZDIFF", "ZDIFFSTORE", "ZINCRBY", "ZINTER", "ZINTERSTORE", "ZLEXCOUNT", "ZPOPMAX", "ZPOPMIN", "ZRANGE", "ZRANGEBYLEX", "ZREVRANGEBYLEX", "ZRANGEBYSCORE", "ZRANK", "ZREM", "ZREMRANGEBYLEX", "ZREMRANGEBYRANK", "ZREMRANGEBYSCORE", "ZREVRANGE", "ZREVRANGEBYSCORE", "ZREVRANK", "ZSCORE", "ZUNION", "ZMSCORE", "ZUNIONSTORE", "ZSCAN"];
export declare type SortedSetsCommandType = typeof SortedSetsCommands[number];
export declare const StreamsCommands: readonly ["XINFO", "XADD", "XTRIM", "XDEL", "XRANGE", "XREVRANGE", "XLEN", "XREAD", "XGROUP", "XREADGROUP GROUP", "XACK", "XCLAIM", "XPENDING"];
export declare type StreamsCommandType = typeof StreamsCommands[number];
export declare const StringsCommands: readonly ["APPEND", "BITCOUNT", "BITFIELD", "BITOP", "BITPOS", "DECR", "DECRBY", "GET", "GETBIT", "GETRANGE", "GETSET", "INCR", "INCRBY", "INCRBYFLOAT", "MGET", "MSET", "MSETNX", "PSETEX", "SET", "SETBIT", "SETEX", "SETNX", "SETRANGE", "STRALGO", "STRLEN"];
export declare type StringsCommandType = typeof StringsCommands[number];
export declare const TransactionCommands: readonly ["DISCARD", "EXEC", "MULTI", "UNWATCH", "WATCH"];
export declare type TransactionCommandType = typeof TransactionCommands[number];
